# Generated by Django 2.2.5 on 2019-09-12 08:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=30)),
                ('terminal', models.CharField(max_length=25)),
                ('service', models.CharField(max_length=15)),
                ('service_type', models.CharField(max_length=25)),
                ('service_provider', models.CharField(max_length=80)),
                ('consignee_name', models.CharField(max_length=35)),
                ('eta_dock', models.DateTimeField(blank=True, null=True)),
                ('dock_confirmed', models.BooleanField(default=False)),
                ('appointment_confirmed', models.BooleanField(default=False)),
                ('delivery_confirmed', models.BooleanField(default=False)),
                ('time_added', models.DateTimeField(default=datetime.datetime.now)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('account_id_num', models.CharField(max_length=25)),
                ('account_name', models.CharField(max_length=25)),
                ('account_ref_num', models.CharField(max_length=20)),
                ('booker_name', models.CharField(max_length=35)),
                ('latest_update', models.CharField(blank=True, max_length=100, null=True)),
                ('is_canceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('timezone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SPContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('off_phone', models.CharField(max_length=30)),
                ('off_ex', models.CharField(max_length=4)),
                ('fax', models.CharField(max_length=10)),
                ('addr', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
                ('time_added', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SPNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('time_added', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DockConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(max_length=25)),
                ('condition_comment', models.CharField(max_length=50)),
                ('time_added', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(max_length=25)),
                ('condition_comment', models.CharField(max_length=50)),
                ('signed_pod', models.ImageField(upload_to='pods/')),
                ('time_added', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('event_name', models.CharField(max_length=100)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('time_added', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_date', models.DateTimeField(blank=True, null=True)),
                ('appt_by_user', models.CharField(max_length=25)),
                ('comment', models.TextField(blank=True, null=True)),
                ('time_added', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.Contract')),
            ],
        ),
    ]
