# Generated by Django 2.2.5 on 2019-09-10 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=25)),
                ('terminal', models.CharField(max_length=25)),
                ('service', models.CharField(max_length=15)),
                ('service_type', models.CharField(max_length=25)),
                ('service_provider', models.CharField(max_length=80)),
                ('consignee_name', models.CharField(max_length=35)),
                ('eta_dock', models.DateTimeField(blank=True)),
                ('dock_confirmed', models.BooleanField(default=False)),
                ('appointment_confirmed', models.BooleanField(default=False)),
                ('delivery_confirmed', models.BooleanField(default=False)),
                ('time_added', models.DateTimeField(default=datetime.datetime.now)),
                ('deadline', models.DateTimeField(blank=True)),
                ('account_id_num', models.CharField(max_length=25)),
                ('account_name', models.CharField(max_length=25)),
                ('account_ref_num', models.CharField(max_length=20)),
                ('booker_name', models.CharField(max_length=35)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
