# Generated by Django 2.2.5 on 2019-09-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='eta_dock',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
