# Generated by Django 2.2.5 on 2019-09-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcontact',
            name='time_added',
        ),
        migrations.RemoveField(
            model_name='spnote',
            name='time_added',
        ),
    ]
