# Generated by Django 2.2.5 on 2019-09-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0002_auto_20190910_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
