# Generated by Django 2.2.5 on 2019-09-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0002_auto_20190912_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='timezone',
        ),
    ]
