# Generated by Django 2.2.5 on 2019-09-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0003_auto_20190910_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('timezone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SPContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('timezone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SPNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='num',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='DockConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_by_user', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(max_length=25)),
                ('condition_comment', models.CharField(max_length=25)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(max_length=25)),
                ('condition_comment', models.CharField(max_length=25)),
                ('signed_pod', models.ImageField(upload_to='pods/')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=25)),
                ('event_name', models.CharField(max_length=25)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('time_added', models.DateTimeField(blank=True, null=True)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentConfirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_date', models.DateTimeField(blank=True, null=True)),
                ('appt_by_user', models.CharField(max_length=25)),
                ('comment', models.TextField(blank=True, null=True)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.Contract')),
            ],
        ),
    ]
