# Generated by Django 2.2.5 on 2019-09-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0004_auto_20190910_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='latest_update',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
