# Generated by Django 2.2.5 on 2019-09-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0005_contract_latest_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
