# Generated by Django 2.2.5 on 2019-09-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0006_contract_is_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dockconfirmed',
            old_name='appt_by_user',
            new_name='delivery_datetime',
        ),
    ]
