# Generated by Django 2.2.5 on 2019-09-11 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0008_auto_20190911_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentconfirmed',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='deliveryconfirmed',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='dockconfirmed',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='spcontact',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='spnote',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='contractupdate',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
