# Generated by Django 2.2.5 on 2019-09-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0009_auto_20190911_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractupdate',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
    ]
