# Generated by Django 2.2.5 on 2019-09-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0010_auto_20190911_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
    ]
