# Generated by Django 2.2.5 on 2019-09-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0010_auto_20190911_1457'),
        ('service_providers', '0004_auto_20190910_1542'),
    ]

    operations = [
    ]
