# Generated by Django 2.2.5 on 2019-09-11 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0011_merge_20190911_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dockconfirmed',
            old_name='appt_by_user',
            new_name='delivery_datetime',
        ),
        migrations.AddField(
            model_name='appointmentconfirmed',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='deliveryconfirmed',
            name='signed_pod',
            field=models.ImageField(default='', upload_to='pods/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryconfirmed',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='dockconfirmed',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='spcontact',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='spnote',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentconfirmed',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractupdate',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractupdate',
            name='time_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryconfirmed',
            name='condition_comment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryconfirmed',
            name='signed_by',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dockconfirmed',
            name='condition_comment',
            field=models.CharField(max_length=50),
        ),
    ]
