# Generated by Django 2.2.5 on 2019-09-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0012_auto_20190911_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spcontact',
            old_name='timezone',
            new_name='addr',
        ),
        migrations.RenameField(
            model_name='spcontact',
            old_name='title',
            new_name='off_phone',
        ),
        migrations.AddField(
            model_name='spcontact',
            name='fax',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spcontact',
            name='fname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spcontact',
            name='lname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spcontact',
            name='off_ex',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
