# Generated by Django 2.2.5 on 2019-09-11 18:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0013_auto_20190911_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.SPNote')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_providers.SPNote')),
            ],
        ),
    ]
