# Generated by Django 2.2.5 on 2019-09-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0014_contactupdate_noteupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteupdate',
            name='note_id',
        ),
        migrations.DeleteModel(
            name='ContactUpdate',
        ),
        migrations.DeleteModel(
            name='NoteUpdate',
        ),
    ]
