# Generated by Django 2.2.5 on 2019-09-11 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_providers', '0015_auto_20190911_1545'),
        ('service_providers', '0011_remove_contract_status'),
    ]

    operations = [
    ]
